<?php

echo "\n";
echo '      </div>' . "\n";
echo '    </div>' . "\n";
echo "\n";
echo '  </div>';
echo '      <!-- Footer -->' . "\n";
echo '      <footer class="">' . "\n";
echo '        <div class="container">' . "\n";
echo '          <div class="copyright text-center my-auto">' . "\n";
echo '             <span><a href="#">IBO AZUL</a> <a href="#"> // &#169;  EDITADO POR BRASIL PROJETOS</a></span>' . "\n";
echo '          </div>' . "\n";
echo '        </div>' . "\n";
echo '      </footer>';
echo '      <!-- End of Footer -->' . "\n";
echo '<script src="https://code.jquery.com/jquery-3.4.1.js"></script>' . "\n";
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>' . "\n";
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>' . "\n";
echo '<script src= "js/switch.js"></script> ' . "\n";
echo '<script src="js/bootstrap-datetimepicker.js"></script>' . "\n";
echo '<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>' . "\n";
echo '</body>' . "\n";
echo "\n";
echo '</html>' . "\n";
echo "\n";
echo '<script type="text/javascript">' . "\n";
echo '$("#form_datetime").datetimepicker({format: \'yyyy-mm-dd hh:ii:ss\', autoclose:true});' . "\n";
echo "\n";
echo '$(document).ready( function () {' . "\n";
echo '    $(\'#Dtable\').DataTable ' . "\n";
echo '                ({' . "\n";
echo '                    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],' . "\n";
echo "\t\t\t\t\t" . '"filter": true,' . "\n";
echo '                    "Paginate": true,' . "\n";
echo "\t\t\t\t\t" . '"ordering": true,' . "\n";
echo '       "searching": true,' . "\n";
echo '       "paging":   true,' . "\n";
echo '       "info":     true' . "\n";
echo '                });' . "\n";
echo '} );' . "\n";
echo "\n";
echo "\n";
echo '$("#menu-toggle").click(function(e) {' . "\n";
echo '  e.preventDefault();' . "\n";
echo '  $("#wrapper").toggleClass("toggled");' . "\n";
echo '});' . "\n";
echo "\n";
echo '$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){' . "\n";
echo '    $("#success-alert").alert(\'close\');' . "\n";
echo '});' . "\n";
echo "\n";
echo '    $(\'#confirm-delete\').on(\'show.bs.modal\', function(e) {' . "\n";
echo '        $(this).find(\'.btn-ok\').attr(\'href\', $(e.relatedTarget).data(\'href\'));' . "\n";
echo '    });' . "\n";
echo "\n";
echo '</script>';
echo '<style>';
echo 'sorting {' . "\n";
echo '    background-repeat: no-repeat;' . "\n";
echo '    background-position: center right;' . "\n";
echo '}';
echo '<style>';

?>